name: dsicord notif

on:
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the time
        id: time
        run:
          NOW=$(date ="%r")
          echo "now=${NOW}" >> $GITHUB_OUTPUT
        env:
          TZ: America/New_York
      - name: Send the time
        uses: satak/webrequest-action@master
        with: 
           url: https://discord.com/api/webhooks/1160366710998696026/CdcDQYe78mRxAx9SYIIwAkuneSeaIeSS01S7NFWEKCm5IGo2lODxOhGmeF41rHO1q-Cf
           method: POST
           payload: '{ "content": "This is a new change ${{ steps.time.outputs.now }}!"}'

      - name: Slack notification
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
           SLACK_CHANNEL: general # Optional. (defaults to webhook)
           SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: 'A new commit has been pushed.'
